from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms#makes use of widgets
from django.contrib.auth.forms import AuthenticationForm
from django.forms.widgets import PasswordInput, TextInput
from .models import Record

#register/create a user

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
    
        #login a user

class LoginForm(AuthenticationForm):
    
    username = forms.CharField(widget=TextInput())
    password = forms.CharField(widget=PasswordInput())

class CreateRecordForm(forms.ModelForm):
    class Meta:
        model = Record 
        fields = ['first_name', 'last_name', 'email', 'phone', 'address', 'city', 'state', 'country']
        #fields needs to be exactly the same as the model

class UpdateRecordForm(forms.ModelForm):
    #has instance attribute
    class Meta:
        model = Record 
        fields = ['first_name', 'last_name', 'email', 'phone', 'address', 'city', 'state', 'country']
        #fields needs to be exactly the same as the model, we dont use creation date on either because it will be auto generated by django when we create a new record 





